// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MinuteMan {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UIImageView __mt_backdrop;
		
		private MonoTouch.UIKit.UIScrollView __mt_scrollView;
		
		private MonoTouch.UIKit.UIPageControl __mt_pager;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("backdrop")]
		private MonoTouch.UIKit.UIImageView backdrop {
			get {
				this.__mt_backdrop = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("backdrop")));
				return this.__mt_backdrop;
			}
			set {
				this.__mt_backdrop = value;
				this.SetNativeField("backdrop", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("scrollView")]
		private MonoTouch.UIKit.UIScrollView scrollView {
			get {
				this.__mt_scrollView = ((MonoTouch.UIKit.UIScrollView)(this.GetNativeField("scrollView")));
				return this.__mt_scrollView;
			}
			set {
				this.__mt_scrollView = value;
				this.SetNativeField("scrollView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("pager")]
		private MonoTouch.UIKit.UIPageControl pager {
			get {
				this.__mt_pager = ((MonoTouch.UIKit.UIPageControl)(this.GetNativeField("pager")));
				return this.__mt_pager;
			}
			set {
				this.__mt_pager = value;
				this.SetNativeField("pager", value);
			}
		}
	}
}
